### ISSUE TITLE
Merge upstream

### ISSUE THREAD

**Issue by dave-kennedy** [koolshare/tinyproxy#1]
Can this be merged upstream to https://github.com/tinyproxy/tinyproxy?

**Comment by jannson** [comment]
This is only an experience version for Merlin firmware in router, and it's a backup repo for myself. Some feature is not need for tinyproxy in other place.

Please use https://github.com/tinyproxy/tinyproxy directly.

**Comment by jannson** [comment]
By the way. the socks5 feature is not supported by myself, it's a patch from google (I found it by google). I just merge it to this repo.
